### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by nowindows** [DusanMadar/PySyncDroid#1]
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup
ImportError: No module named setuptools

**Comment by DusanMadar** [comment]
I just tried to install it in a `Python 2.7.6` _virtualenv_ on `Xubuntu 14.04` and it there was no problem during the setup.

What are your system details?

**Comment by nowindows** [comment]
That did the trick for the install!  Sorry I missed it. FYI, I'm using Linux Mint Mate 17.3.
I have Samsung Model SM-G360V.  Is Vendor and Model case insensitive?  So, do I use -V samsung  -M sm-g360v?
Thank you for this software!  I tried PureSync on Windozzzzee.  Incredibly slow!!!

**Comment by DusanMadar** [comment]
No problem.

I am ignoring case when searching for the device, so it doesn't matter as long as model and vendor are correct.
