### ISSUE TITLE
How do I find the Vendor and Model for my device?

### ISSUE THREAD

**Issue by nowindows** [DusanMadar/PySyncDroid#2]
I have Samsung Galaxy Core Prime SM-G360V connected.  Linux Mint Mate 17.3. In the Caja browser, at the top of the browser it says "SAMSUNG-SM-G360V".  Location bar says mtp://[usb:005,003]/.  Then I see Card and Phone in the file browser.

The phone model also shows on the device under Settings/About phone - Phone Name SAMSUNG-SM-G360V, Model Number SM-G360V.

I've tried all kinds of permutations of the phone Model and keep getting "not found" messages:
pysyncdroid -ov -V Samsung -M SM-G360V -s /media/joe/Media/Music -d /Card/Music
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/find_device.py", line 48, in connection_details
pysyncdroid.exceptions.DeviceException: Device "Samsung SM-G360V" not found.

pysyncdroid -ov -V Samsung -M SAMSUNG-SM-G360V -s /media/joe/Media/Music -d /Card/Music
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/find_device.py", line 48, in connection_details
pysyncdroid.exceptions.DeviceException: Device "Samsung SAMSUNG-SM-G360V" not found

How do I find the correct Vendor and Model for my device?

Thanks!

**Comment by nowindows** [comment]
Additional information. 
Browser shows: mtp://[usb:005,003]/Card/Music
mount shows: gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,user=joe)

pysyncdroid -ov -V Samsung -M android -s /media/joe/Media/Music -d /Card/Music
pysyncdroid.exceptions.DeviceException: Device "Samsung android" not found

Tried -V samsung -M g360v, -V samsung -M g360v, samsung -M sm-G360v, ...

Thanks,
Joe

**Comment by DusanMadar** [comment]
Hmm, I suppose not all phones are using the same `vendor` & `model` combination when connected to a computer. I tested this only with my own phone.

I am using `Settings/About device - Model Number`.

But to be sure how the computer see's your device, run the following command: `lsub` and please post the output.

**Comment by nowindows** [comment]
Settings/About phone gives Model Number as SM-G360V.  Which is what I tried.

On my computer lsusb gives.
Bus 005 Device 003: ID 04e8:6860 Samsung Electronics Co., Ltd GT-I9100 Phone [Galaxy S II], GT-I9300 Phone [Galaxy S III], GT-P7500 [Galaxy Tab 10.1]

So, now we're making progress:
pysyncdroid -ov -V Samsung -M GT-I9100 -s /media/joe/Media/Music -d /Card/Music

works for a while then says.

Creating directory /Card/Music/
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 49, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 169, in sync
  File "build/bdist.linux-x86_64/egg/pysyncdroid/gvfs.py", line 28, in mkdir
  File "build/bdist.linux-x86_64/egg/pysyncdroid/utils.py", line 38, in run_bash_cmd
pysyncdroid.exceptions.BashException: Command "gvfs-mkdir -p /Card/Music/" failed: Error creating directory: Error creating directory: Permission denied

So now it's the problem of the Android 5.1.1 not giving pysncdroid write permission for the phone.  I've given other apps permission to write to phone.  I'm not sure how to allow psyncdroid permission to write to the phone???

**Comment by nowindows** [comment]
With the phone mounted, I can drag and drop files from my browser to mtp://[usb:005,003]/Card/Music, or anywhere else on Phone or Card with no problem.

**Comment by DusanMadar** [comment]
Ok, so model `SM-G360V` is a Verizon version of one of the Galaxy series, interesting.

**Comment by nowindows** [comment]
It comes down to - how do I give permission on the phone for pysncdroid to write to it.

**Comment by DusanMadar** [comment]
Are you able to create directories on your phone from the computer file manager?

**Comment by nowindows** [comment]
Yes, I just created mtp://[usb:005,003]/Phone/Music/AC_DC. No problem.
pysyncdroid -ov -V Samsung -M GT-I9100 -s /media/joe/Media/Music/AC_DC -d /Phone/Music/AC_DC
Creating directory /Phone/Music/AC_DC/Back_In_Black
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 49, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 169, in sync
  File "build/bdist.linux-x86_64/egg/pysyncdroid/gvfs.py", line 28, in mkdir
  File "build/bdist.linux-x86_64/egg/pysyncdroid/utils.py", line 38, in run_bash_cmd
pysyncdroid.exceptions.BashException: Command "gvfs-mkdir -p /Phone/Music/AC_DC/Back_In_Black" failed: Error creating directory: Error creating directory: Permission denied

**Comment by DusanMadar** [comment]
Try `sudo pysyncdroid -ov -V Samsung -M GT-I9100 -s /media/joe/Media/Music/AC_DC -d /Phone/Music/AC_DC`

**Comment by nowindows** [comment]
When I run that on computer it shows the copying progressing for all the media with no errors.  But the music doesn't show on the actual phone or one computer at mtp://[usb:005,003]/Phone/Music/AC_DC

sudo pysyncdroid -ov -V Samsung -M GT-I9100 -s /media/joe/Media/Music/AC_DC -d /Phone/Music/AC_DC
Creating directory /Phone/Music/AC_DC/Back_In_Black
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3 to /Phone/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Have_A_Drink_On_Me.mp3 to /Phone/Music/AC_DC/Back_In_Black/Have_A_Drink_On_Me.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Rock_And_Roll_Aint_Noise_Poll.mp3 to /Phone/Music/AC_DC/Back_In_Black/Rock_And_Roll_Aint_Noise_Poll.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Let_Me_Put_My_Love_Into_You.mp3 to /Phone/Music/AC_DC/Back_In_Black/Let_Me_Put_My_Love_Into_You.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Back_In_Black.mp3 to /Phone/Music/AC_DC/Back_In_Black/Back_In_Black.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Shoot_To_Thrill.mp3 to /Phone/Music/AC_DC/Back_In_Black/Shoot_To_Thrill.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/folder.jpg to /Phone/Music/AC_DC/Back_In_Black/folder.jpg 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/You_Shook_Me_All_Night_Long.mp3 to /Phone/Music/AC_DC/Back_In_Black/You_Shook_Me_All_Night_Long.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/What_Do_You_Do_For_Money_Honey.mp3 to /Phone/Music/AC_DC/Back_In_Black/What_Do_You_Do_For_Money_Honey.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Hells_Bells.mp3 to /Phone/Music/AC_DC/Back_In_Black/Hells_Bells.mp3 
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Shake_A_Leg.mp3 to /Phone/Music/AC_DC/Back_In_Black/Shake_A_Leg.mp3 
Creating directory /Phone/Music/AC_DC/Highway_To_Hell
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Girls_Got_Rhythm.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Girls_Got_Rhythm.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Get_It_Hot.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Get_It_Hot.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Walk_All_Over_You.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Walk_All_Over_You.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Highway_To_Hell.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Highway_To_Hell.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Touch_Too_Much.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Touch_Too_Much.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Beating_Around_The_Bush.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Beating_Around_The_Bush.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Shot_Down_In_Flames.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Shot_Down_In_Flames.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/If_You_Want_Blood_Youve_Got_It.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/If_You_Want_Blood_Youve_Got_It.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/folder.jpg to /Phone/Music/AC_DC/Highway_To_Hell/folder.jpg 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Love_Hungry_Man.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Love_Hungry_Man.mp3 
Copying /media/joe/Media/Music/AC_DC/Highway_To_Hell/Night_Prowler.mp3 to /Phone/Music/AC_DC/Highway_To_Hell/Night_Prowler.mp3

**Comment by nowindows** [comment]
The computer is happy but I still think the phone needs to allow permission to write to it.

When I installed any app on phone that wrote to phone, I had to give permission on phone to allow writing to phone.  I think that I need to do this for pysyncdroid but don't know how.

**Comment by DusanMadar** [comment]
Yes, that is because you used `/Phone/Music/AC_DC`. So if you go to that path on your computer, you will see that the files were copied.

Do not use the leading `/` when copying files to the phone.

**Please check my previous response, it's updated**.

**Comment by nowindows** [comment]
sudo pysyncdroid -ov -V Samsung -M GT-I9100 -s /media/joe/Media/Music/AC_DC -d Phone/Music/AC_DC
Creating directory /run/user/0/gvfs/mtp:host=%5Busb%3A005%2C003%5D/Phone/Music/AC_DC/Back_In_Black
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3 to /run/user/0/gvfs/mtp:host=%5Busb%3A005%2C003%5D/Phone/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3 ...


But mtp://[usb:005,003]/Phone/Music/AC_DC directory still empty even though computer says files were copied.  Empty with computer file manager and empty on phone with X-plore.

**Comment by nowindows** [comment]
Now I can't open android in computer - lost connection.

After reconnect I get:
 sudo pysyncdroid -ov -V Samsung -M GT-I9100 -s /media/joe/Media/Music/AC_DC -d Phone/Music/AC_DC
Copying /media/joe/Media/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3 to /run/user/0/gvfs/mtp:host=%5Busb%3A005%2C007%5D/Phone/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3 
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 49, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 184, in sync
  File "build/bdist.linux-x86_64/egg/pysyncdroid/gvfs.py", line 54, in cp
  File "build/bdist.linux-x86_64/egg/pysyncdroid/utils.py", line 38, in run_bash_cmd
pysyncdroid.exceptions.BashException: Command "gvfs-copy /media/joe/Media/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3 /run/user/0/gvfs/mtp:host=%5Busb%3A005%2C007%5D/Phone/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3" failed: Error copying file /media/joe/Media/Music/AC_DC/Back_In_Black/Givin_The_Dog_A_Bone.mp3: Error splicing file: No space left on device

Even though I have 1.9GB free.

**Comment by DusanMadar** [comment]
Remove the directory from your phone and  try running `pysyncdroid` **without** `sudo`, i.e. `pysyncdroid -ov -V Samsung -M GT-I9100 -s /media/joe/Media/Music/AC_DC -d Phone/Music/AC_DC`.

I think that you cannot see the files in the create directory because you are not logged in to your phone with super user rights.

**Comment by nowindows** [comment]
Ok that worked with empty directory on phone.

Now what I really want to do is sync computer Music with Music on Card.  I already have 32GB on Computer and Card and want to update with about 90MB of new music from Computer to Card.

AC_DC on card is already the same as on computer.  When I do
pysyncdroid -ov -V Samsung -M GT-I9100 -s /media/joe/Media/Music/AC_DC -d Card/Music/AC_DC
computer shows Copying for all 24 mp3's or 81GB.  Is this proper operation since I used v option even though both Computer and Card had same content?

**Comment by DusanMadar** [comment]
81GB for 24 files?

And yes, it is a proper operation, you are using the `-o` flag which is means overwrite existing files.

Remove the `-o` flag, i.e. `pysyncdroid -v -V Samsung -M GT-I9100 -s /media/joe/Media/Music/AC_DC -d Card/Music/AC_DC` and this time nothing will be copied.

**Comment by nowindows** [comment]
As a test I just added a single mp3 to a folder in computer Music and ran psyncdroid and it copied the single file.
I still get a "Copying" message for every file that exists on both computer and card, in addition to the single file that actually got copied.

**Comment by DusanMadar** [comment]
Yes, explained in my previous response.

Use `pysyncdroid -h` to display description for each of available flags.

**Comment by nowindows** [comment]
Your response came through slowly.  Sorry, sometimes it takes me a while.

Ok great.  So it all came down to getting the correct model of the phone and me understanding the options.  User error again.  THANK YOU for your patience and this GREAT application!

As you can see from my username, now I'm getting very close to that (nowindows) end.  I do as little (only one) Windozzze applications as I need in Virtualbox on Linux.  So, now the only thing that I do on my Windozze computer is use the Samsung backup application for  backup.  Do you have a suggestion for how I can do this backup/restore (restore if I need it)  of all phone data on Linux?

FYI.  When I tried to copy all 32GB of Music from Linux to Card attached to USB adapter, I would get errors. So, eventually I did the full copy on the Windozze computer using USB adapter for microSD card.

FYI. BlackPlayer works great on phone!

Thanks Again!
Joe

**Comment by DusanMadar** [comment]
Yes, comments are a little slow.

Been there, done that so I understand that the command line can be an _arcane spell book_, especially in the beginning. 

Can you please provide more details about the errors you got when trying to copy 32GB's of data? I also sometimes get errors (`gvfs` related, to be specific ), but I am unable to debug (don't know how to reproduce this).

**Comment by nowindows** [comment]
I can't really remember the specifics of the errors gvfs or mtp I think.  I was a while ago.
I got brave and just did:
pysyncdroid -v  -V Samsung -M GT-I9100 -s /media/joe/Media/Music/ -d Card/Music/ -u remove

It wiped out 80% of my music until I killed the process.  What did I do wrong and how do I safely get the Music back to the card?

**Comment by DusanMadar** [comment]
You have used the ` -u remove` flag which removed _all unmatched files_, i.e. files, which were present only on the device, but not on the computer, as you were syncing the device with what is on your computer.

I don't know hot to restore removed files on `Andorid`.

**Comment by nowindows** [comment]
I'm trying to sync from the computer music to the Card on the phone (the computer being the master copy) deleting any files on the Card that are not on the computer.  What exact command should I use?

When I used the following command, it ran for a while: It first deleted some files on the Card that were on the Computer then copied files from the computer to the Card and then errored out with the error below (it copied only about 3GB out of the 31GB total):

pysyncdroid -v  -V Samsung -M GT-I9100 -s /media/joe/Media/Music -d Card/Music -u remove

ERROR shown on computer from above command after some deletions and copying.

Copying /media/joe/Media/Music/Jars_of_Clay/Good_Monsters/folder.jpg to /run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C011%5D/Card/Music/Jars_of_Clay/Good_Monsters/folder.jpg 
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 49, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 184, in sync
  File "build/bdist.linux-x86_64/egg/pysyncdroid/gvfs.py", line 54, in cp
  File "build/bdist.linux-x86_64/egg/pysyncdroid/utils.py", line 38, in run_bash_cmd
pysyncdroid.exceptions.BashException: Command "gvfs-copy /media/joe/Media/Music/Jars_of_Clay/Good_Monsters/folder.jpg /run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C011%5D/Card/Music/Jars_of_Clay/Good_Monsters/folder.jpg" failed: Error copying file /media/joe/Media/Music/Jars_of_Clay/Good_Monsters/folder.jpg: The name :1.1146 was not provided by any .service files

An addition nice feature is to have an exclude option as rsync has.  I don't want to copy the *.jpg files from computer to Card :)

**Comment by nowindows** [comment]
Tried to get all the files copied with:
 pysyncdroid -v  -V Samsung -M GT-I9100 -s /media/joe/Media/Music -d Card/Music

Ran for a while the gave following error:

Creating directory /run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C003%5D/Card/Music/The_Temptations/The_Temptations_Sing_Smokey_1998_Reissu
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 49, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 169, in sync
  File "build/bdist.linux-x86_64/egg/pysyncdroid/gvfs.py", line 28, in mkdir
  File "build/bdist.linux-x86_64/egg/pysyncdroid/utils.py", line 38, in run_bash_cmd
pysyncdroid.exceptions.BashException: Command "gvfs-mkdir -p /run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C003%5D/Card/Music/The_Temptations/The_Temptations_Sing_Smokey_1998_Reissu" failed: Error creating directory: Directory doesn't exist

Is there a size limitation on folder or file names?

When I then tried to access Card/Music in computer file manager I get window:  "The folder contents could not be displayed.  Sorry could not display all the contents of "Music": libmtp error: couild not get object handles"

I read somewhere that libmtp has bugs in it.

**Comment by nowindows** [comment]
Now it's "dead". Issuing the following command sits for several minutes then gives error.

pysyncdroid -v  -V Samsung -M GT-I9100 -s /media/joe/Media/Music -d Card/Music
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 49, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 173, in sync
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C003%5D/Card/Music/'

I think libmtp is the problem. I hope that I don't have to go to Windoze to get the music back on Card.

**Comment by DusanMadar** [comment]
> I'm trying to sync from the computer music to the Card on the phone (the computer being the master copy) deleting any files on the Card that are not on the computer. What exact command should I use?

In that case you have used the right command, i.e.

`pysyncdroid -v -V Samsung -M GT-I9100 -s /media/joe/Media/Music/ -d Card/Music/ -u remove`

> An addition nice feature is to have an exclude option as rsync has. I don't want to copy the *.jpg files from computer to Card :)

I certainly can add this feature.

> Is there a size limitation on folder or file names?

> I think libmtp is the problem. I hope that I don't have to go to Windoze to get the music back on Card.

Good point, but I am not sure. I think what you are hitting with the errors you provided has something to do with the stuff under the hood of Linux.

**Comment by nowindows** [comment]
Another error:
 pysyncdroid -v  -V Samsung -M GT-I9100 -s /media/joe/Media/Music -d Card/Music
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 49, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 173, in sync
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C003%5D/Card/Music/'

**Comment by nowindows** [comment]
"I think what you are hitting with the errors you provided has something to do with the stuff under the hood of Linux."

Yeah, that's what I was suspicious of all along.  Your app is fine but I think that there are libmtp bugs.

I tried dismounting the phone and rebooting computer and reconnecting phone and still get errors.

I'm going to the Windoze machine to get the Music back on the phone :(

**Comment by DusanMadar** [comment]
I just tried to make a backup of my Card/Music directory

`pysyncdroid -V samsung -M gt-i9300 -s Card/Music -d ~/Desktop/card_music_bak -v`

and got a `gvfs` related error for a change

`pysyncdroid.exceptions.BashException: Command "gvfs-copy /run/user/1000/gvfs/mtp:host=%5Busb%3A001%2C013%5D/Card/Music/<very_long_name>.mp3 /home/dm/Desktop/card_music_bak/<very_long_name>.mp3" failed: Error copying file /run/user/1000/gvfs/mtp:host=%5Busb%3A001%2C013%5D/Card/Music/<very_long_name>.mp3: Error while getting peer-to-peer dbus connection: Error receiving data: Connection reset by peer`

**Comment by nowindows** [comment]
Yeah - what can we do about that???  Who does libmtp and gvfs - Linus?

As I said I kept running into errors when copying large amounts of files to Card in Linux.  I remember people complaining about that and hoping that Rhythmbox would do syncing. I use Clementine.

Phone is currently hooked up to Windozzzzzzzzzzzze computer copying 32GB of music back to phone - says "About 3 Hours remaining"!!!!!!

Now I recall that when I was syncing music to a SansaClipPlus a couple of years ago that I ran into folder/file name lengths - I think it was 39?  I also had to write scripts to fix folder and file names - remove "special characters", replace spaces with _, etc. for the Sansa to work properly (I actually used Rockbox on the Sansa).

As I recall, it turned out that having Folder and File names without spaces and shorter than 40 characters did the trick.

**Comment by nowindows** [comment]
Also my experience on mtp with Linux is that if you don't do "too much" at a time (whatever that means) then it is successful.

So, after I get all the music back using WindoZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZe then I can maybe use your script to do the little syncs - maybe maybe.

**Comment by nowindows** [comment]
Thanks for you patience and persistence!

I spent the whole day yesterday rebuilding one "critical" raspberry pi (my backup pi) and redoing all of the ssh keys on the pi's (they were a mess).  I have close to 20 raspberry pi's running at the moment.

So, I'm tired of this stuff, for now.  I'm going for a walk - without my phone:)

Thanks again!  Happy syncing!

**Comment by DusanMadar** [comment]
I don't know who does `libmtp` and `gvfs`, but I know that `MTP` is a windows thing: https://en.wikipedia.org/wiki/Media_Transfer_Protocol

> Also my experience on mtp with Linux is that if you don't do "too much" at a time (whatever that means) then it is successful.

Exactly, if you are going slow it works OK. Well, kind of. 

> Thanks for you patience and persistence!

And thank you for really helpful testing and debugging, it's greatly appreciated.

**Comment by nowindows** [comment]
If we could only understand what "slow" means, maybe adding delays somewhere might help.

WindoZZZZZZZZZZZZZZZZZZZZZZZZZZZZZe says 2 hours and 5 minutes remaining.  It'll be a long walk. So long - until I get back from my walk.

My goal is to get this syncing thing working easily, somehow, on Linux for my family.

I refuse to buy any electronic device that starts with a small letter i!  Android is, so far acceptable.

**Comment by nowindows** [comment]
Windoze only would copy 27GB of the 37GB (using drag and drop) to the phone as an mtp device.  It seems that the only sure way to get this much data on the Card is to remove the card and copy to it.

**Comment by DusanMadar** [comment]
Awesome, no wonder `Linux` is having issues with this when `Windows` itself can't leverage `MTP` properly.

BTW, I am now able to resolve the 

`gvfs-copy ... Error while getting peer-to-peer dbus connection: Error receiving data: Connection reset by peer`

it seems that when this happens the `mtp` device is unmounted, but you can fix this mounting it again with

`gvfs-mount mtp://[usb:<usb bus id>,<device id>]/` (e.g. `gvfs-mount mtp://[usb:001,016]/`)

I need to implement and test if this really fixes the problem. I would rather prevent it from happening, but I guess this is will have to be a _good enough_ solution.

**Comment by nowindows** [comment]
Good.  I'm trying to learn more about mtp and gvfs myself.  Thanks!

**Comment by nowindows** [comment]
Once you can handle some of the problems of mtp and gvfs* then I can use your script to back up the Phone and the Card - like the Samsung Windows Backup app - I think?  Gotta research this.

Do you handle hidden files?

**Comment by DusanMadar** [comment]
So I just tested handling the 

`Error while getting peer-to-peer dbus connection: Error receiving data: Connection reset by peer`

with a re-mount and it seems like it works. I was able to make a backup of my phone's music library. Copied 20.5GB (3113) files. Tested twice, both runs successful.

> Do you handle hidden files?

Python's `os.walk()` is used to get the list of files and that function includes both hidden files and directories.

**Comment by nowindows** [comment]
Ok, I try it. Thanks.

I was wondering if your script handles updates of files that have just
changed in size or just the date has changed?

**Comment by DusanMadar** [comment]
> I was wondering if your script handles updates of files that have just changed in size or just the date has changed?

None of mentioned is handled. I started small and simple - only the file presence is considered.

**Comment by nowindows** [comment]
I'm not sure if that can be accomplished.  Have to look into gvfs-info
and gvfs-ls. :)
