### ISSUE TITLE
Another BashException

### ISSUE THREAD

**Issue by nowindows** [DusanMadar/PySyncDroid#3]
Using latest PySyncDroid error:
Copying /media/joe/Media/Music/Skillet/Comatose/folder.jpg to /run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C003%5D/Card/Music/Skillet/Comatose/folder.jpg
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 50, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 215, in sync
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 139, in gvfs_wrapper
  File "build/bdist.linux-x86_64/egg/pysyncdroid/gvfs.py", line 54, in cp
  File "build/bdist.linux-x86_64/egg/pysyncdroid/utils.py", line 38, in run_bash_cmd
pysyncdroid.exceptions.BashException: Command "gvfs-copy /media/joe/Media/Music/Skillet/Comatose/folder.jpg /run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C003%5D/Card/Music/Skillet/Comatose/folder.jpg" failed: Error copying file /media/joe/Media/Music/Skillet/Comatose/folder.jpg: The name :1.1976 was not provided by any .service files

Needed to remount after the above error.

**Comment by nowindows** [comment]
Needed to remount after the above error.

**Comment by nowindows** [comment]
Why not leave out line 141 and 146 in sync.py?

**Comment by DusanMadar** [comment]
So, in case of the `The name :<name> was not provided by any .service files` we can just retry the `copy` and then continue the sync, right?

**Comment by nowindows** [comment]
Yes it appears that that "might" work.  I'll do more testing.

**Comment by DusanMadar** [comment]
OK, there is only one problem. I didn't came across this issue so far, therefore I cannot test it. But I still have to try copy a couple of GBs from computer to phone, as that is what you are doing when this happens.

**Comment by nowindows** [comment]
Latest Error:

pysyncdroid -v -V Samsung -M GT-I9100 -s /media/joe/Media/Music/ -d Card/Music/ -u remove
Gathering the list of files to synchronize, this may take a while ...
Traceback (most recent call last):
  File "/usr/local/bin/pysyncdroid", line 9, in <module>
    load_entry_point('pysyncdroid==0.0.1', 'console_scripts', 'pysyncdroid')()
  File "build/bdist.linux-x86_64/egg/pysyncdroid/cli.py", line 50, in main
  File "build/bdist.linux-x86_64/egg/pysyncdroid/sync.py", line 204, in sync
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/mtp:host=%5Busb%3A005%2C002%5D/Card/Music/'

**Comment by nowindows** [comment]
Since I had problems with PySyncDroid I needed to do some testing.

I do BASH and C, rather than Python, so I wrote a little BASH script to do the syncronization from Computer to Samsung and easily do testing (something that I understand and am comfortable with).  I take advantage of find, sed, grep, and awk to make the script very simple.

I'm intending to do syncronization from computer to Samsung (of a large amount of music) and delete files on Samsung that are not found on Computer and "update" any "newer" file from Computer to Samsung (Computer being the "master").

First - Android issues.
Samsung Galaxy Tab 3 has Android 4.4 KitKat and does not allow writing to the external SD card (without rooting the device).  gvfs-ls, gvfs-tree, etc. will work, but anything that tries to write to "Card" will not work.
Samsung SM-G30V has Android version 5.1.1 Lollipop which does allow reading and writing to Card.

Finding all the mp3's on the Computer is just a simple: find $musicPathOnComputer -type f -iname "*.mp3".  Finding all of the mp3's on the Samsung is another issue. There are different ways of doing this.

There are 7453 files in 2664 directories currently in the Music folder (36.5GB), for a total of 10,096 executions of gvfs-ls (one possible approach) to find all of the files on the Samsung Device.  I have an additional ~10GB of music, currently in an Archive folder that I may also like to sync.  A "large" amount of music.

Music is arranged as Artist(s)/Album(s)/Song(s).

Findings:
1. - Using gvfs-tree mtp://[usb:005,005]/Card/Music fails about a third of the way through the 10,096 folders and files with the error - "(gvfs-tree:20778): GLib-ERROR **: Creating pipes for GWakeup: Too many open files Trace/breakpoint trap"
2. - Using gvfs-ls to loop through the Artists and then using gvfs-tree within each Artist also fails part way through.
3. - Using gvfs-ls to loop through Artists/Albums/Songs speeds along through about the first 1000 entries and then the following error appears: "Error: Error while getting peer-to-peer dbus connection: Error receiving data: Connection reset by peer".  After this, gvfs-ls becomes very slow!  It would take hours to complete the process (maybe the Windoze transfer - that I described earlier - suffered from a similar problem).
4. - "Small" file transfers, using gvfs-cp, etc. seem to work without problems.

I've tried to explore solutions (inserting time delays in the code, etc.) to the above "problems" but have not found a solution yet.

Highlighting mtp://[usb:005,005]/Card/Music in Linux file manager (Caja 1.12.1) and the pressing * * * to expand the Music folder to display all Artists, Albums, and Songs takes several minutes, but eventually completes and displays the entire folder structure including all mp3's!  So, I'm not sure what Caja uses to do this successfully?

Currently trying a different approach.  Computer is Music "MASTER".
New Approach:
1. Use find and stat to create a timestamped (timestamp for each mp3) list of all music on Computer for transfer to Samsung.
2. Copy timestamped list to Samsung.
3. Do "full" copy of all Music from computer to Samsung Card (by extracting the microSD card from phone and doing copy).  Computer and Samsung identical at this point.
4. At next sync - generate updated timestamped list of all Computer music, retrieve list from Samsung, compare lists then update new/changed music to Samsung, update Samsung timestamped music list and then transfer new list to Samsung.
5. Repeat.

Comments?

**Comment by DusanMadar** [comment]
Can't reproduce `The name :<name> was not provided by any .service files`.

When trying to sync PC to Device and it takes a _bit longer_ (10+ minutes), I get the following:

`Message did not receive a reply (timeout by message bus)`

and the device is _disconnected_. I need to _unlock the device again_ to re-connect it back again and then continue the sync process.

It seems like the _device drops the MTP connection_ after a certain amount of time.

**Comment by nowindows** [comment]
As long as there are no gvfs* errors, then things run to ok.

My new (successful) procedure is to initially copy all music from pc to card (so they are identical).  Then, I run a very small bash script, ~50 lines, to keep track of music on computer and card.  Then script syncs new music to card and deletes music from card.  Log files on computer and card (with timestamp for each song) are used for each subsequent sync.

Can't beat the simplicity of bash!  Just wrote bash script to populate the lyrics frames in my entire music library from the web.
